backend:
  name: git-gateway
  branch: main

media_folder: "images/products"
public_folder: "/images/products"

collections:
  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Marca", name: "brand", widget: "string" }

      - label: "Categoría"
        name: "category"
        widget: "select"
        options:
          - guantes
          - vendas
          - cascos
          - protectores
          - sacos
          - ropa
          - accesorios
          - mma

      - { label: "Precio", name: "price", widget: "number" }

      - label: "Stock"
        name: "stock"
        widget: "select"
        options:
          - available
          - low
          - soldout

      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Características", name: "features", widget: "list" }
      - { label: "Tallas", name: "sizes", widget: "list" }
      - { label: "Colores", name: "colors", widget: "list" }